import{a as p,S as $,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";const q="51662095-362d68f1fb432ef34c7441ea2",y=15;async function h(t,i=1){const{data:r}=await p.get("",{params:{key:q,per_page:y,page:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r}let f;const v=document.getElementById("gallery"),g=document.getElementById("loader"),b=document.getElementById("moreBtn");function L(t=[]){const i=t.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:a,comments:x,downloads:S})=>`
      <li class="photo-card">
        <a class="gallery__item" href="${n}">
          <img class="gallery__image" src="${r}" alt="${e}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${a}</li>
          <li><b>Comments:</b> ${x}</li>
          <li><b>Downloads:</b> ${S}</li>
        </ul>
      </li>`).join("");v.insertAdjacentHTML("beforeend",i),f?f.refresh():f=new $("#gallery a",{captionsData:"alt",captionDelay:250})}function C(){const t=document.querySelector("#gallery");t&&(t.innerHTML="")}function w(){g.classList.remove("is-hidden")}function B(){g&&g.classList.add("is-hidden")}function P(){b.classList.remove("is-hidden")}function d(){b.classList.add("is-hidden")}const E=document.querySelector("form"),l=E.querySelector('button[type="submit"]'),m=document.querySelector("#moreBtn");let u="",s=1;E.addEventListener("submit",async t=>{if(t.preventDefault(),u=new FormData(t.target).get("searchText").trim(),s=1,d(),!u){c.error({position:"center",title:"Помилка",message:"Ви нічого не ввели!"});return}const i=l.textContent;l.disabled=!0,l.textContent="Searching…",C(),w();try{const r=await h(u,s),{hits:n,total:e}=r;if(console.log(`totalHits: ${e}`),n.length===0){c.warning({position:"center",title:"Немає результатів",message:"Нічого не знайдено."}),d();return}L(n),s*y<e?P():(d(),c.info({position:"bottomCenter",title:"Кінець",message:"Більше немає результатів."}))}catch(r){console.log(r),c.error({position:"center",title:(r==null?void 0:r.message)||"Помилка запиту",message:"Спробуйте ще раз пізніше."})}finally{B(),l.disabled=!1,l.textContent=i,t.target.reset()}});m.addEventListener("click",async()=>{m.disabled=!0,s+=1,w();try{const t=await h(u,s);L(t.hits);const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"}),s*y>=t.total&&(d(),c.info({position:"bottomCenter",title:"Кінець",message:"Це всі результати за запитом."}))}catch(t){console.log(t)}finally{B(),m.disabled=!1}});
//# sourceMappingURL=index.js.map
